name: Release All Charts

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: metacontroller/metacontroller
          ref: v2.0.12

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Install releaser
        run: |
          mkdir -p $HOME/_releaser/
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_${v1.2.1#v}_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz -C "$HOME/_releaser/"
          rm -f cr.tar.gz

          echo 'Adding cr directory to PATH...'
          export PATH="$HOME/_releaser/:$PATH"

      - name: Package
        run:  cr package "deploy/helm/metacontroller/" --package-path .cr-release-packages

#      - name: Run chart-releaser
#        uses: helm/chart-releaser-action@v1.2.1
#        with:
#          charts_dir: "deploy/helm/"
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
