name: Release All Charts

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - v2.0.0
          - v2.0.1
          - v2.0.10
          - v2.0.11
          - v2.0.12
          - v2.0.2
          - v2.0.3
          - v2.0.4
          - v2.0.5
          - v2.0.6
          - v2.0.7
          - v2.0.8
          - v2.0.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: metacontroller/metacontroller
          ref: ${{ matrix.tag }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Install releaser
        run: |
          mkdir -p $HOME/cr/
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz -C "$HOME/cr/"
          rm -f cr.tar.gz

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            try {
              await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/${{ matrix.tag }}",
                sha: context.sha
              })
            } catch (e) {
              console.log(e);
            }

      - name: Package
        if: always()
        run: |
          $HOME/cr/cr package "deploy/helm/metacontroller/" --package-path .cr-release-packages
          $HOME/cr/cr upload -o orf -r metacontroller-chart --skip-existing
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Archive release
        uses: actions/upload-artifact@v2
        with:
          name: .cr-release-packages
          path: .cr-release-packages/

  update-index:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Install releaser
        run: |
          mkdir -p $HOME/cr/
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz -C "$HOME/cr/"
          rm -f cr.tar.gz

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Update index
        run: |
          $HOME/cr/cr index -o orf -r metacontroller-chart --push -c "https://orf.github.io/metacontroller-chart"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
